In [1]:
import pandas as pd
import csv

In [2]:
result_fname = 'result.csv'

In [3]:
df = pd.read_csv(result_fname)
df

,style,code,label,processed
0,Aligned with opening delimiter.,"bar = another_long_function(arg_one, arg_two,\...",correct,True
1,Aligned with opening delimiter.,"baz = yet_another_function(param1, param2,\r\n...",correct,True
2,Aligned with opening delimiter.,"qux = some_other_function(first_arg, second_ar...",correct,True
3,Aligned with opening delimiter.,"quux = a_different_function(argument1, argumen...",correct,True
4,Aligned with opening delimiter.,"corge = function_with_args(arg_a, arg_b,\r\n ...",correct,True
...,...,...,...,...
135,No extra indentation (same level of indent).,if (this_is_one_thing and\r\n that_is_anot...,wrong,True
136,No extra indentation (same level of indent).,if (this_is_one_thing and\r\n that_is_another...,wrong,True
137,No extra indentation (same level of indent).,if (this_is_one_thing and\r\n that_is_a...,wrong,True
138,No extra indentation (same level of indent).,if (variable_name and\r\n another_variable_n...,wrong,True
139,No extra indentation (same level of indent).,if (this_is_true and\r\n that_is_also_true):,wrong,True

In [30]:
df_filtered = df[df['processed'] == True]
df_filtered

,style,code,label,processed
0,Aligned with opening delimiter.,"bar = another_long_function(arg_one, arg_two,\...",correct,True
1,Aligned with opening delimiter.,"baz = yet_another_function(param1, param2,\r\n...",correct,True
2,Aligned with opening delimiter.,"qux = some_other_function(first_arg, second_ar...",correct,True
3,Aligned with opening delimiter.,"quux = a_different_function(argument1, argumen...",correct,True
4,Aligned with opening delimiter.,"corge = function_with_args(arg_a, arg_b,\r\n ...",correct,True
...,...,...,...,...
135,No extra indentation (same level of indent).,if (this_is_one_thing and\r\n that_is_anot...,wrong,True
136,No extra indentation (same level of indent).,if (this_is_one_thing and\r\n that_is_another...,wrong,True
137,No extra indentation (same level of indent).,if (this_is_one_thing and\r\n that_is_a...,wrong,True
138,No extra indentation (same level of indent).,if (variable_name and\r\n another_variable_n...,wrong,True
139,No extra indentation (same level of indent).,if (this_is_true and\r\n that_is_also_true):,wrong,True

In [31]:
N = len(df.index)
N_filtered = len(df_filtered.index)

f'{N - N_filtered} items have been filtered out as unprocessed.'

'0 items have been filtered out as unprocessed.'

In [28]:
df_filtered.to_csv(result_fname, mode='w', index=False, quoting=csv.QUOTE_ALL)